-- Create a new database named 'ecommerce'
CREATE DATABASE ecommerce;

-- Select the ecommerce database for use
USE ecommerce;

-- Display all tables inside the ecommerce database
SHOW TABLES;
-- Create a master table that consolidates customer, order, product,
-- payment, and revenue information into a single analytical table

CREATE TABLE consolidated_dataset (
    customer_id INT,
    order_id INT PRIMARY KEY,
    order_date DATE,
    product_category_name_translation VARCHAR(200),
    product_name VARCHAR(200),
    category VARCHAR(200),
    quantity INT,
    revenue DECIMAL(10,2),
    payment_type VARCHAR(50)
);
-- View the structure, column names, and datatypes
DESCRIBE consolidated_dataset;
-- Convert customer_id to VARCHAR to match source dataset
ALTER TABLE consolidated_dataset 
MODIFY customer_id VARCHAR(50);

-- Convert order_id to VARCHAR for consistency
ALTER TABLE consolidated_dataset 
MODIFY order_id VARCHAR(50);

-- Convert order_date to DATETIME to store timestamp
ALTER TABLE consolidated_dataset 
MODIFY order_date DATETIME;

-- Rename corrupted column name (encoding issue fix)
ALTER TABLE product_category_name_translation
RENAME COLUMN ï»¿product_category_name
TO product_category_name;

-- Remove existing primary key
ALTER TABLE consolidated_dataset
DROP PRIMARY KEY;

-- Add new auto-increment surrogate primary key
ALTER TABLE consolidated_dataset
ADD COLUMN id INT AUTO_INCREMENT PRIMARY KEY FIRST;

-- Insert consolidated data by joining multiple normalized tables:
-- customers, orders, order_items, products, payments

-- This transforms transactional data into an analytics-ready dataset

 INSERT INTO consolidated_dataset 
SELECT
    -- Customer Information
    c.customer_id,

    -- Order Information
    o.order_id,
    o.order_purchase_timestamp AS order_date,

    -- Product Information
    pct.product_category_name_english,
    p.product_id,
    p.product_category_name,

    -- Quantity
    oi.order_item_id,

    -- Revenue = Product Price + Freight
    (oi.price + oi.freight_value),

    -- Payment Method
    pay.payment_type

FROM olist_orders_dataset o
JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id   -- Foreign key relationship
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
JOIN olist_products_dataset p
    ON oi.product_id = p.product_id
LEFT JOIN product_category_name_translation pct
    ON p.product_category_name = pct.product_category_name
JOIN olist_order_payments_dataset pay
    ON o.order_id = pay.order_id;
    
    -- Create table to store total lifetime revenue per customer
CREATE TABLE customer_lifetime_value (
    customer_id VARCHAR(100),
    customer_lifetime_value DECIMAL(10,2)
);

-- Calculate total revenue generated by each customer
INSERT INTO customer_lifetime_value
SELECT
    customer_id,
    SUM(revenue) AS customer_lifetime_value
FROM consolidated_dataset
GROUP BY customer_id
ORDER BY customer_lifetime_value DESC;

-- Create a professional analytical view for Customer CLV metrics

CREATE VIEW customer_clv AS
SELECT 
    customer_id,

    -- Total Revenue Generated
    SUM(revenue) AS total_revenue,

    -- Total Orders Placed
    COUNT(DISTINCT order_id) AS total_orders,

    -- First Purchase Date
    MIN(order_date) AS first_purchase,

    -- Last Purchase Date
    MAX(order_date) AS last_purchase,

    -- Customer Lifespan in Days
    DATEDIFF(MAX(order_date), MIN(order_date)) AS lifespan_days

FROM consolidated_dataset
GROUP BY customer_id;

-- This query calculates monthly revenue per product
-- and ranks products within each month using RANK()

SELECT *
FROM (
    SELECT
        product_name AS product_id,

        -- Extract Year-Month format
        DATE_FORMAT(order_date,'%y-%m') AS order_date,

        -- Total monthly revenue per product
        SUM(revenue) AS total_revenue,

        -- Rank products within each month
        RANK() OVER(
            PARTITION BY DATE_FORMAT(order_date,'%y-%m')
            ORDER BY SUM(revenue) DESC
        ) AS product_rank

    FROM consolidated_dataset
    GROUP BY product_id, order_date

) AS ranked_products

-- Keep only Top 10 products per month
WHERE product_rank <= 10

-- Sort results
ORDER BY order_date, product_rank;

-- Identify first purchase date and cohort month per customer

SELECT
    customer_id,
    MIN(order_date) AS first_purchase_date,
    DATE_FORMAT(MIN(order_date), '%Y-%m') AS cohort_month
FROM consolidated_dataset
GROUP BY customer_id;

-- Calculate how many months after first purchase
-- each subsequent purchase occurred

SELECT
    cd.customer_id,
    DATE_FORMAT(cd.order_date, '%Y-%m') AS purchase_month,
    DATE_FORMAT(fp.first_purchase_date, '%Y-%m') AS cohort_month,

    -- Month difference calculation
    PERIOD_DIFF(
        DATE_FORMAT(cd.order_date, '%Y%m'),
        DATE_FORMAT(fp.first_purchase_date, '%Y%m')
    ) AS month_number

FROM consolidated_dataset cd
JOIN (
    SELECT
        customer_id,
        MIN(order_date) AS first_purchase_date
    FROM consolidated_dataset
    GROUP BY customer_id
) fp
ON cd.customer_id = fp.customer_id;

-- Count distinct customers per cohort month and month number

INSERT INTO cohort_analysis
SELECT
    DATE_FORMAT(fp.first_purchase_date, '%Y-%m') AS cohort_month,

    PERIOD_DIFF(
        DATE_FORMAT(cd.order_date, '%Y%m'),
        DATE_FORMAT(fp.first_purchase_date, '%Y%m')
    ) AS month_number,

    COUNT(DISTINCT cd.customer_id) AS total_customers

FROM consolidated_dataset cd
JOIN (
    SELECT
        customer_id,
        MIN(order_date) AS first_purchase_date
    FROM consolidated_dataset
    GROUP BY customer_id
) fp
ON cd.customer_id = fp.customer_id

GROUP BY cohort_month, month_number
ORDER BY cohort_month, month_number;

-- Create churn detection table
CREATE TABLE detect_churn_customers (
    customer_id VARCHAR(50),
    last_purchase_date VARCHAR(50),
    months_inactive VARCHAR(50),
    customer_status VARCHAR(50)
);

-- Insert churn status based on inactivity threshold (>= 3 months)

INSERT INTO detect_churn_customers
SELECT
    customer_id,

    -- Most recent purchase
    MAX(order_date) AS last_purchase_date,

    -- Months inactive since latest dataset date
    PERIOD_DIFF(
        DATE_FORMAT((SELECT MAX(order_date) FROM consolidated_dataset), '%Y%m'),
        DATE_FORMAT(MAX(order_date), '%Y%m')
    ) AS months_inactive,

    -- Classification logic
    CASE 
        WHEN PERIOD_DIFF(
                DATE_FORMAT((SELECT MAX(order_date) FROM consolidated_dataset), '%Y%m'),
                DATE_FORMAT(MAX(order_date), '%Y%m')
             ) >= 3 
        THEN 'Churned'
        ELSE 'Active'
    END AS customer_status

FROM consolidated_dataset
GROUP BY customer_id;



